### ISSUE TITLE
Build a specific version

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/Docker-Docs#73]
Hi,

currently, 7.2.2-1 is the latest version used in your helm chart but if i do a build right now, using this repo, i will have images based on the 7.3.0 version.
Is there a way to specify which version i want to build ?

Thanks.
Yoann.

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

To define the build version, you need to add `PRODUCT_URL` argument with the required release version to `build.sh` script.
e.g. `--build-arg PRODUCT_URL=https://download.onlyoffice.com/install/documentserver/linux/onlyoffice-documentserver$PRODUCT_EDITION-7.2.2.x86_64.rpm`

**Comment by ydelattre** [comment]
Hello,
Thanks for the answer and adding RELEASE_VERSION in the dockerfile. It's much clearer :)
Regards.
Yoann
